"""Utilities for the Olist payment analytics project."""

from .model import (
    DEFAULT_CLUSTER_FEATURES,
    DEFAULT_NUMERIC_FEATURES,
    DEFAULT_PAYMENT_PREFIX,
    POST_DELIVERY_NUMERIC_FEATURES,
    PRE_DELIVERY_NUMERIC_FEATURES,
    build_roc_curve_figure,
    build_segment_profile_figure,
    build_revenue_at_risk_map,
    build_revenue_at_risk_table,
    compute_shap_artifacts,
    fit_customer_segments,
    get_numeric_feature_set,
    plot_shap_summary,
    prepare_satisfaction_dataset,
    run_full_ml_workflow,
    score_customer_risk,
    score_cluster_counts,
    prepare_intervention_payload,
    train_vip_weighted_xgboost,
    train_satisfaction_models,
)

__all__ = [
    "DEFAULT_CLUSTER_FEATURES",
    "DEFAULT_NUMERIC_FEATURES",
    "DEFAULT_PAYMENT_PREFIX",
    "POST_DELIVERY_NUMERIC_FEATURES",
    "PRE_DELIVERY_NUMERIC_FEATURES",
    "build_roc_curve_figure",
    "build_segment_profile_figure",
    "build_revenue_at_risk_map",
    "build_revenue_at_risk_table",
    "compute_shap_artifacts",
    "fit_customer_segments",
    "get_numeric_feature_set",
    "plot_shap_summary",
    "prepare_satisfaction_dataset",
    "run_full_ml_workflow",
    "score_customer_risk",
    "score_cluster_counts",
    "prepare_intervention_payload",
    "train_vip_weighted_xgboost",
    "train_satisfaction_models",
]
